### ISSUE TITLE
FIIO X 7 user

### ISSUE THREAD

**Issue by BearGor** [LudySu/LrcJaeger#3]
Hi, im a FIIO X 7 user and i found that this app can't search any file in the latest version of X7 (FW3.0.8_beta Android 5.1). Thank you.

**Comment by LudySu** [comment]
Hi @BearGor thanks for your report. FIIO X7 is a very good HiFi player but unfortunately I don't have one in hand, and as you might know FIIO might have modified the Android OS quite a lot, so can you confirm is it that you can't see music files or can't search? 

If you can't see the music files, because the app relies on the local multimedia file database in Android, so it could be the case FIIO has an alternative so the app can't get music file information out of it. In that case, I can't do anything at the moment.

Thanks,
Ludy
